//
// Created by macbookpro on 4/26/21.
//

#ifndef RIGHTHELPER_NV12RGBA_H
#define RIGHTHELPER_NV12RGBA_H
static const char * nv12rgba_vs = "#version 300 es\n"
                                   "layout(location = 0) in vec2 aPosition;\n"
                                   "layout(location = 1) in vec2 aTexcoord0;\n"
                                   "uniform vec2 texcoordClip;\n"
                                   "out vec2 v_texCoord;\n"
                                   "out vec2 v_texCoord1;\n"
                                   "void main()\n"
                                   "{\n"
                                   "    gl_Position =  vec4(aPosition, 1.0, 1.0);\n"
                                   "    v_texCoord = (aTexcoord0 - 0.5)*texcoordClip + 0.5;\n"
                                   "}";

static const char * nv12rgba_fs = "#version 300 es\n"
                                   "precision highp float;\n"
                                   "in vec2 v_texCoord;\n"
                                   "layout(location = 0) out vec4 outColor;\n"
                                   "uniform sampler2D utexture0;\n"
                                   "uniform sampler2D utexture1;\n"
                                   "\n"
                                   "void main()\n"
                                   "{\n"
                                   "        vec3 yuv;\n"
                                   "        yuv.x = texture(utexture0, v_texCoord).r;\n"
                                   "        yuv.y = texture(utexture1, v_texCoord).r - 0.5;\n"
                                   "        yuv.z = texture(utexture1, v_texCoord).a - 0.5;\n"
                                   "        highp vec3 rgb = mat3(1.0,       1.0,     1.0,\n"
                                   "        0.0, \t-0.344, \t1.770,\n"
                                   "        1.403,  -0.714,     0.0) * yuv;\n"
                                   "        outColor = vec4(rgb, 1.0);\n"
                                   "}";

static const char * nv12rgba_alpha_fs = "#version 300 es\n"
                                        "precision highp float;\n"
                                        "in vec2 v_texCoord;\n"
                                        "layout(location = 0) out vec4 outColor;\n"
                                        "uniform sampler2D utexture0;\n"
                                        "uniform sampler2D utexture1;\n"
                                        "uniform float uMaxTexCoord;\n"
                                        "\n"
                                        "void main()\n"
                                        "{\n"
                                        "        vec2 alphaCoord = vec2(v_texCoord.x * (uMaxTexCoord / 2.0), v_texCoord.y);\n"
                                        "        vec2 rgbCoord = vec2(v_texCoord.x * (uMaxTexCoord / 2.0) + (uMaxTexCoord / 2.0), v_texCoord.y);\n"
                                        "        vec3 yuv;\n"
                                        "        yuv.x = texture(utexture0, rgbCoord).r;\n"
                                        "        yuv.y = texture(utexture1, rgbCoord).r - 0.5;\n"
                                        "        yuv.z = texture(utexture1, rgbCoord).a - 0.5;\n"
                                        "        highp vec3 rgb = mat3(1.0,       1.0,     1.0,\n"
                                        "        0.0, \t-0.344, \t1.770,\n"
                                        "        1.403,  -0.714,     0.0) * yuv;\n"
                                        "        outColor = vec4(rgb, texture(utexture0, alphaCoord).r); \n"
                                        "}";

static const char * nv12rgba_vap_fs = "#version 300 es\n"
                                        "precision highp float;\n"
                                        "in vec2 v_texCoord;\n"
                                        "layout(location = 0) out vec4 outColor;\n"
                                        "uniform sampler2D utexture0;\n"
                                        "uniform sampler2D utexture1;\n"
                                        "uniform vec4 uAlphaRect;\n"
                                        "uniform vec4 uRGBRect;\n"
                                        "\n"
                                        "void main()\n"
                                        "{\n"
                                        "        vec2 alphaCoord = vec2("
                                        "                                  v_texCoord.x * (uAlphaRect.z - uAlphaRect.x) + uAlphaRect.x, "
                                        "                                  v_texCoord.y * (uAlphaRect.w - uAlphaRect.y) + uAlphaRect.y"
                                        "                              );\n"
                                        "        vec2 rgbCoord = vec2("
                                        "                                  v_texCoord.x * (uRGBRect.z - uRGBRect.x) + uRGBRect.x, "
                                        "                                  v_texCoord.y * (uRGBRect.w - uRGBRect.y) + uRGBRect.y"
                                        "                             );\n"
                                        "        vec3 yuv;\n"
                                        "        yuv.x = texture(utexture0, rgbCoord).r;\n"
                                        "        yuv.y = texture(utexture1, rgbCoord).r - 0.5;\n"
                                        "        yuv.z = texture(utexture1, rgbCoord).a - 0.5;\n"
                                        "        highp vec3 rgb = mat3(1.0,       1.0,     1.0,\n"
                                        "        0.0, \t-0.344, \t1.770,\n"
                                        "        1.403,  -0.714,     0.0) * yuv;\n"
                                        "        outColor = vec4(rgb, texture(utexture0, alphaCoord).r); \n"
                                        "}";
#endif //RIGHTHELPER_NV12RGBA_H
